name: Continuous integration

on:
  pull_request:
  push:
      branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  os_tests:
    name: "Tests/OS: ${{ matrix.os }} - ${{ matrix.channel }}-${{ matrix.rust_target }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        exclude:
        - os: macos-10.15
          rust_target: x86_64-gnu
        - os: macos-10.15
          rust_target: x86_64-msvc
        - os: windows-2019
          rust_target: x86_64-apple-darwin
        - os: ubuntu-20.04
          rust_target: x86_64-msvc
        - os: ubuntu-20.04
          rust_target: x86_64-apple-darwin
        channel:
        - stable
        - beta
        - nightly
        - 1.34.0
        os:
        - macos-10.15
        - windows-2019
        - ubuntu-20.04
        rust_target: 
        - x86_64-gnu
        - x86_64-msvc
        - x86_64-apple-darwin
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        override: true
        profile: minimal
        toolchain: ${{ matrix.channel }}-${{ matrix.rust_target }}

    - name: Build with --no-default-features 
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --no-default-features
    - name: Test with --no-default-features 
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-default-features
    
    - name: Build with --all-features 
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features
    - name: Test with --all-features 
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features
    
    - name: Build with default features 
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Test with default features 
      uses: actions-rs/cargo@v1
      with:
        command: test
    
    - name: Build with --features guid
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features guid
    - name: Test with --features guid 
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features guid
    
    - name: Build with --features serde
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features serde
    - name: Test with --features serde 
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features serde
    
    - name: Build with --features slog
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features slog
    - name: Test with --features slog 
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features slog
      
    - name: Build with --features v1
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features v1
    - name: Test with --features serde 
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features v1
    
    - name: Build with --features v3
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features v3
    - name: Test with --features v3 
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features v3
    
    - name: Build with --features v4
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features v4
    - name: Test with --features v4 
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features v4
    
    - name: Build with --features v5
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features v5
    - name: Test with --features v5 
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features v5
