name: Clippy

on: [push, pull_request]

jobs:
  linux-clippy:
   name: Linux
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Install Toolchain
       uses: actions-rs/toolchain@v1
       with:
         components: clippy
         override: true
         profile: minimal
         toolchain: 1.34.0
     - name: Run `cargo clippy`
       uses: actions-rs/cargo@v1
       with:
         command: clippy
         args: --features "serde slog std v1 v3 v4 v5" -- -D warnings
  windows-clippy:
   name: Windows
   runs-on: windows-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Install Toolchain
       uses: actions-rs/toolchain@v1
       with:
         components: clippy
         override: true
         profile: minimal
         toolchain: 1.34.0
     - name: Run `cargo clippy`
       uses: actions-rs/cargo@v1
       with:
         command: clippy
         args: --features "guid serde slog std v1 v3 v4 v5" -- -D warnings
